---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - triton.ml.triton
  resources:
  - serverclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - triton.ml.triton
  resources:
  - serverclasses/finalizers
  verbs:
  - update
- apiGroups:
  - triton.ml.triton
  resources:
  - serverclasses/status
  verbs:
  - get
  - patch
  - update
