name: Pull Request Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Lint and test app build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker buildx build triton-operator-controller:latest .
